### PR TITLE
fix(ui): remove broken delete-dialog refs and unsupported HeadersTable prop

### PR DESCRIPTION
**Pull request by terafin**
## Summary

Fixes three TypeScript errors introduced by #3986 (dynamic MCP library catalog) that break `npm run build-enterprise` and consequently the Docker image build (`transports/Dockerfile`, `ui-builder` stage). The errors only surface during a real build (`vite build` runs `tsc`) — they aren't caught by `npm run dev`'s loose checking.

The failing build (Docker, against `dev` HEAD) emits:

```
app/workspace/mcp-registry/library/views/mcpLibraryInstallSheet.tsx(469,11): error TS2322: Type '{ ... fixedKeys: string[]; ... }' is not assignable to type 'IntrinsicAttributes & HeadersTableProps<string>'.
  Property 'fixedKeys' does not exist on type 'IntrinsicAttributes & HeadersTableProps<string>'.
app/workspace/mcp-registry/library/views/mcpLibraryServerCard.tsx(8,40): error TS2307: Cannot find module './mcpLibraryDeleteDialog' or its corresponding type declarations.
app/workspace/mcp-registry/library/views/mcpLibraryServersTable.tsx(8,40): error TS2307: Cannot find module './mcpLibraryDeleteDialog' or its corresponding type declarations.
app/workspace/mcp-registry/library/views/mcpLibraryServersTable.tsx(85,12): error TS2304: Cannot find name 'canDelete'.
app/workspace/mcp-registry/library/views/mcpLibraryServersTable.tsx(92,31): error TS2304: Cannot find name 'setServerToDelete'.
app/workspace/mcp-registry/library/views/mcpLibraryServersTable.tsx(96,17): error TS2304: Cannot find name 'Trash2'.
```

## Changes (minimum-touch)

1. **`mcpLibraryServerCard.tsx`** — drop unused `import { MCPLibraryDeleteDialog } from "./mcpLibraryDeleteDialog"`. The module does not exist anywhere in the tree, and the import is never referenced in JSX.
2. **`mcpLibraryServersTable.tsx`** — same unused import removed, and a dead delete-button block removed. The block referenced `canDelete`, `setServerToDelete`, and `Trash2`, none of which are declared as props, hooks/state, or imports.
3. **`mcpLibraryInstallSheet.tsx`** — remove `fixedKeys={server.stdio_config.envs}` from one `<HeadersTable />`. `HeadersTableProps` (`ui/components/ui/headersTable.tsx`) does not declare a `fixedKeys` prop, so this fails type-check.

Net diff: **+1/−22**.

## If a delete feature was intended

The pattern of these errors strongly suggests an in-progress "remove from library" feature that landed mid-way: the dialog file was never committed, the supporting props/state were never wired, and the `Trash2` icon was never imported. This patch restores buildability today; a follow-up that ships the dialog component, the props, the local state, and the icon import together is the right place to land that feature.

Same comment applies to the `fixedKeys` prop on `HeadersTable` — if envs from `stdio_config` should be pre-populated as fixed keys, that's a HeadersTable enhancement plus the prop wiring; out of scope for restoring the build.

## Test plan

- [x] Identified all three error sites in the failing build log.
- [x] Verified each fix removes the relevant error without changing rendered behavior (the deleted code paths were dead — `canDelete` was never truthy, `MCPLibraryDeleteDialog` was never rendered, and the `fixedKeys` prop was silently dropped before this typecheck-strict path).
- [ ] `npm run build-enterprise` from `ui/` succeeds. (Maintainers: please confirm in CI.)
- [ ] `docker build -f transports/Dockerfile .` succeeds. (Maintainers: please confirm in CI.)

## Summary by CodeRabbit

* **Refactor**
  * Streamlined MCP library interface by removing redundant server actions and cleaning up unused components in the library views.

### CODE REVIEW

**Comment by akshaydeo** [comment]
this is already fixed
