### PR TITLE
fix(modelcatalog): define helpers + struct fields referenced by mcp_library_sync.go

### PR DESCRIPTION
**Pull request by terafin**
## Problem

PR #3979 added `framework/modelcatalog/mcp_library_sync.go` but referenced ~10 symbols that exist in neither the `modelcatalog` package nor any importable location. `go build` against `transports/Dockerfile` (production multi-stage build) fails on every dev commit since #3979:

```
framework/modelcatalog/mcp_library_sync.go:60:35: undefined: urlFetchMaxRetries
framework/modelcatalog/mcp_library_sync.go:60:55: undefined: urlFetchMaxBackoff
framework/modelcatalog/mcp_library_sync.go:80:12: undefined: slug
framework/modelcatalog/mcp_library_sync.go:83:9:  undefined: slug
framework/modelcatalog/mcp_library_sync.go:87:25: undefined: slug
framework/modelcatalog/mcp_library_sync.go:105:68: undefined: slug
framework/modelcatalog/mcp_library_sync.go:141:5: mc.syncMu undefined (type *ModelCatalog has no field or method syncMu)
framework/modelcatalog/mcp_library_sync.go:142:5: mc.lastMCPLibrarySyncedAt undefined
framework/modelcatalog/mcp_library_sync.go:143:5: mc.syncMu undefined
```

Plus `maxMCPLibraryBodyBytes`, `WithRetries`, `Slugify` — all referenced, none defined. CI doesn't catch this because there's no build-on-push workflow that exercises `transports/Dockerfile`; `pr-tests.yml` is `workflow_dispatch`-only and last passed 2025-11-14.

`Dockerfile.local` works because `go.work` references local module paths and bypasses go.sum, but that's a pre-release fallback per its own header.

## Fix

1. **New file `framework/modelcatalog/mcp_library_helpers.go`** with:
   - Constants `urlFetchMaxRetries`, `urlFetchMaxBackoff`, `retryBackoffMin`, `maxMCPLibraryBodyBytes` (mirroring the unexported equivalents in `framework/modelcatalog/datasheet`).
   - `Slugify(name string) string` — lowercase + collapse non-alphanumeric runs into `-`.
   - `WithRetries[T any](ctx, maxRetries, maxBackoff, op)` — exponential-backoff retry helper, copied from `datasheet/types.go:491` (`withRetries`) and exported because the call site in `mcp_library_sync.go` uses the exported name.

2. **`main.go` ModelCatalog struct** gains three fields referenced by `mcp_library_sync.go`:
   - `mcpLibraryURL string` (read by `getMCPLibraryURL`, set by config plumbing)
   - `syncMu sync.RWMutex` (serializes URL reads + `lastMCPLibrarySyncedAt` updates)
   - `lastMCPLibrarySyncedAt time.Time` (set by `ForceReloadMCPLibrary` after a successful sync)

3. **`mcp_library_sync.go` loop body** now computes `slug := Slugify(e.Name)` at the top of each iteration, with an early-skip when the slug comes out empty (e.g. punctuation-only `Name`).

## Verification

Compiles cleanly under Go 1.26.4 in a `transports/Dockerfile` (production) build. The defaults for `mcpLibraryURL` (empty → falls through to `DefaultMCPLibraryURL` at line 57 of `mcp_library_sync.go`, which is already defined in `config.go:75`) preserve current runtime behavior.

No behavior change for anyone NOT using the MCP library catalog sync path; the new fields are zero-valued unless `ForceReloadMCPLibrary` is invoked.

## Companion issue

Filed separately: a class issue documenting the broader problem that PR #3979 wasn't caught — `pr-tests.yml` has been failing since November 2025 and no push-to-dev workflow exercises the production Dockerfile.

## Summary by CodeRabbit

* **New Features**
  * Added MCP library sync state and last-sync timestamp for improved telemetry and visibility.
  * Built-in retry mechanism with exponential backoff for more resilient operations.
  * Consistent name-to-slug conversion for catalog entry deduplication and to skip invalid names.

* **Chores**
  * Added a manual one-shot tidy workflow to refresh module metadata on demand.
  * Updated transport dependency versions.

### CODE REVIEW

**Comment by Pratham-Mishra04** [comment]
Hey @terafin thanks for the quick fix but its already fixed in #3987 so closing this🙇🏼‍♂️

**Comment by terafin** [comment]
Hey @Pratham-Mishra04 — appreciate the fast triage 🙏 Wanted to follow up post-#3987 merge with empirical results, since the production build path on `dev` is still red. Different symbol than what #4273 originally targeted, but same area, so flagging here rather than opening a fresh issue.

I rebuilt `intarweb/bifrost` against fresh `dev` (synced from `e8986467...` at 2026-06-11T06:39 UTC) with both Dockerfiles:

**`transports/Dockerfile` (canonical / multi-stage):** fails on missing `go.sum` entries — the modelcatalogresolver pseudo-version itself, plus transitive AWS / GCP modules:
```
bifrost-http/handlers/realtime_client_secrets.go:14:2:
  github.com/maximhq/bifrost/plugins/modelcatalogresolver@v0.0.0-20260531215024-856c9963e662:
  missing go.sum entry for go.mod file
... + aws-sdk-go-v2@v1.41.12, smithy-go@v1.27.1, cloud.google.com/go/iam@v1.7.0 (same)
```
Build log: https://github.com/intarweb/bifrost/actions/runs/27328859551

**`transports/Dockerfile.local` (workspace-resolved):** `ResolveProviderFromCatalog` IS defined in `plugins/modelcatalogresolver/main.go:140` on dev tip, but `Dockerfile.local`'s `go work use ...` block omits `./plugins/modelcatalogresolver`, so go falls back to the published pseudo-version which doesn't export that symbol:
```
bifrost-http/handlers/webrtc_realtime.go:171:48:
  undefined: modelcatalogresolver.ResolveProviderFromCatalog
bifrost-http/handlers/webrtc_realtime.go:203:48:        (same)
bifrost-http/handlers/webrtc_realtime.go:1240:48:       (same)
bifrost-http/handlers/realtime_client_secrets.go:235:48: (same)
```
Build log: https://github.com/intarweb/bifrost/actions/runs/27328995915

So #3987 did resolve what #4273 originally pointed at (slug / syncMu / urlFetchMaxRetries / WithRetries) — confirmed those compile errors are gone. But a related break landed on the modelcatalogresolver wiring side after that.

Two surgical fixes look sufficient:
1. Add `go work use ./plugins/modelcatalogresolver` to `transports/Dockerfile.local`'s workspace list (one line).
2. Run `go mod tidy` in `transports/` against current dev to repair `go.sum` for the modelcatalogresolver pseudo-version + transitive AWS/GCP entries. The `tidy-oneshot.yml` workflow from #4273 was meant to mechanize exactly this — happy to extract just that piece into a fresh PR if useful.

Happy to PR either or both — let me know what'd be easiest on your end.
